// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/oauth/callback": {
            "get": {
                "description": "Exchanges the authorization code for tokens and stores them encrypted in SQLite.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Handle Tesla OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth state parameter",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OAuth successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "missing state, code, or cookie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "exchange or persistence error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/oauth/start": {
            "get": {
                "description": "Redirects the user to Tesla's OAuth authorization page. Sets a state cookie for CSRF protection.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Start Tesla OAuth flow",
                "responses": {
                    "302": {
                        "description": "Redirect to Tesla OAuth",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/is-charging": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns whether the configured Tesla vehicle is currently charging. Errors map to false.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charging"
                ],
                "summary": "Check if vehicle is charging",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ChargingResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpapi.ChargingResponse": {
            "type": "object",
            "properties": {
                "is_charging": {
                    "type": "boolean"
                }
            }
        },
        "httpapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tesla Charger Status API",
	Description:      "Service that wraps the Tesla Fleet API to report vehicle charging state.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
